# Decorations, effects, animations, overview, and hot corners.
# Documentation:
#   https://docs.noctalia.dev/umbriel/appearance/
#   https://docs.noctalia.dev/umbriel/animation/
#   https://docs.noctalia.dev/umbriel/workspaces-overview/
#   https://docs.noctalia.dev/umbriel/keybinds/#hot-corners

[appearance]
prefer_no_csd = true
border_width = 2
outer_border_width = 0
corner_radius = 10
drag_opacity = 0.75

[appearance.blur]
enabled = true
optimized = true
passes = 3
radius = 3
noise = 0.02
brightness = 0.9
contrast = 0.9
saturation = 1.1

[appearance.shadow]
enabled = true
softness = 10
offset_x = 2
offset_y = 2

[animation]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.windows_in]
enabled = true
duration_ms = 150
curve = "easeout"
style = "popin"
scale = 0.85

[animation.windows_out]
enabled = true
duration_ms = 150
curve = "easeout"
style = "fade"

[animation.windows_move]
enabled = true
duration_ms = 250
curve = "snappy"

[animation.workspaces]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.overview]
enabled = true
duration_ms = 250
curve = "easeout"
workspace_curve = "spring:1,1000"

[animation.scratchpad]
enabled = true
duration_ms = 250
curve = "easeout"
dim = 0.5
blur = false
scale = 0.0
maximize = false
fullscreen = false

[animation.border]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.dim_unfocused]
enabled = true
duration_ms = 250
curve = "easeout"
dim = 0.0

[animation.layers]
enabled = true
duration_ms = 250
curve = "easeout"

[animation.beziers]

[animation.springs]

[overview]
zoom = 0.5
scroll_factor_horizontal = 1.0
scroll_factor_vertical = 1.0

[hot_corners.top_left]
enabled = true
delay_ms = 500
action = "overview-open"

[hot_corners.top_right]
enabled = true
delay_ms = 500
action = "overview-close"

[hot_corners.bottom_left]
enabled = true
delay_ms = 500
action = "overview-toggle"

[hot_corners.bottom_right]
enabled = true
delay_ms = 500
action = "spawn:notify-send 'Bottom right'"
